### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [3]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [5]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [30]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [6]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [24]:
#This action is importing a module and creating an alias for the NumPy package so it can be referred to as np instead of numpy

1

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [8]:
print(car.shape)
print(mpg.shape)
print(cylinders.shape)
#gives rows by columns (each array is 406 rows by 1 column)

(406,)
(406,)
(406,)


In [12]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)

1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [3]:
print(mpg)

[18.  15.  18.  16.  17.  15.  14.  14.  14.  15.   0.   0.   0.   0.
  0.  15.  14.   0.  15.  14.  24.  22.  18.  21.  27.  26.  25.  24.
 25.  26.  21.  10.  10.  11.   9.  27.  28.  25.  25.   0.  19.  16.
 17.  19.  18.  14.  14.  14.  14.  12.  13.  13.  18.  22.  19.  18.
 23.  28.  30.  30.  31.  35.  27.  26.  24.  25.  23.  20.  21.  13.
 14.  15.  14.  17.  11.  13.  12.  13.  19.  15.  13.  13.  14.  18.
 22.  21.  26.  22.  28.  23.  28.  27.  13.  14.  13.  14.  15.  12.
 13.  13.  14.  13.  12.  13.  18.  16.  18.  18.  23.  26.  11.  12.
 13.  12.  18.  20.  21.  22.  18.  19.  21.  26.  15.  16.  29.  24.
 20.  19.  15.  24.  20.  11.  20.  21.  19.  15.  31.  26.  32.  25.
 16.  16.  18.  16.  13.  14.  14.  14.  29.  26.  26.  31.  32.  28.
 24.  26.  24.  26.  31.  19.  18.  15.  15.  16.  15.  16.  14.  17.
 16.  15.  18.  21.  20.  13.  29.  23.  20.  23.  24.  25.  24.  18.
 29.  19.  23.  23.  22.  25.  33.  28.  25.  25.  26.  27.  17.5 16.
 15.5 14.5 22.  22. 

In [4]:
print(mpg * 12)
np.multiply(mpg,12)


[216.  180.  216.  192.  204.  180.  168.  168.  168.  180.    0.    0.
   0.    0.    0.  180.  168.    0.  180.  168.  288.  264.  216.  252.
 324.  312.  300.  288.  300.  312.  252.  120.  120.  132.  108.  324.
 336.  300.  300.    0.  228.  192.  204.  228.  216.  168.  168.  168.
 168.  144.  156.  156.  216.  264.  228.  216.  276.  336.  360.  360.
 372.  420.  324.  312.  288.  300.  276.  240.  252.  156.  168.  180.
 168.  204.  132.  156.  144.  156.  228.  180.  156.  156.  168.  216.
 264.  252.  312.  264.  336.  276.  336.  324.  156.  168.  156.  168.
 180.  144.  156.  156.  168.  156.  144.  156.  216.  192.  216.  216.
 276.  312.  132.  144.  156.  144.  216.  240.  252.  264.  216.  228.
 252.  312.  180.  192.  348.  288.  240.  228.  180.  288.  240.  132.
 240.  252.  228.  180.  372.  312.  384.  300.  192.  192.  216.  192.
 156.  168.  168.  168.  348.  312.  312.  372.  384.  336.  288.  312.
 288.  312.  372.  228.  216.  180.  180.  192.  180.  192.  168

array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [5]:
print(mpg / 3)
np.divide(mpg,3)

[ 6.          5.          6.          5.33333333  5.66666667  5.
  4.66666667  4.66666667  4.66666667  5.          0.          0.
  0.          0.          0.          5.          4.66666667  0.
  5.          4.66666667  8.          7.33333333  6.          7.
  9.          8.66666667  8.33333333  8.          8.33333333  8.66666667
  7.          3.33333333  3.33333333  3.66666667  3.          9.
  9.33333333  8.33333333  8.33333333  0.          6.33333333  5.33333333
  5.66666667  6.33333333  6.          4.66666667  4.66666667  4.66666667
  4.66666667  4.          4.33333333  4.33333333  6.          7.33333333
  6.33333333  6.          7.66666667  9.33333333 10.         10.
 10.33333333 11.66666667  9.          8.66666667  8.          8.33333333
  7.66666667  6.66666667  7.          4.33333333  4.66666667  5.
  4.66666667  5.66666667  3.66666667  4.33333333  4.          4.33333333
  6.33333333  5.          4.33333333  4.33333333  4.66666667  6.
  7.33333333  7.          8.66666667  7.33

array([ 6.        ,  5.        ,  6.        ,  5.33333333,  5.66666667,
        5.        ,  4.66666667,  4.66666667,  4.66666667,  5.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        5.        ,  4.66666667,  0.        ,  5.        ,  4.66666667,
        8.        ,  7.33333333,  6.        ,  7.        ,  9.        ,
        8.66666667,  8.33333333,  8.        ,  8.33333333,  8.66666667,
        7.        ,  3.33333333,  3.33333333,  3.66666667,  3.        ,
        9.        ,  9.33333333,  8.33333333,  8.33333333,  0.        ,
        6.33333333,  5.33333333,  5.66666667,  6.33333333,  6.        ,
        4.66666667,  4.66666667,  4.66666667,  4.66666667,  4.        ,
        4.33333333,  4.33333333,  6.        ,  7.33333333,  6.33333333,
        6.        ,  7.66666667,  9.33333333, 10.        , 10.        ,
       10.33333333, 11.66666667,  9.        ,  8.66666667,  8.        ,
        8.33333333,  7.66666667,  6.66666667,  7.        ,  4.33

In [6]:
mpg ** 4

array([ 104976.    ,   50625.    ,  104976.    ,   65536.    ,
         83521.    ,   50625.    ,   38416.    ,   38416.    ,
         38416.    ,   50625.    ,       0.    ,       0.    ,
             0.    ,       0.    ,       0.    ,   50625.    ,
         38416.    ,       0.    ,   50625.    ,   38416.    ,
        331776.    ,  234256.    ,  104976.    ,  194481.    ,
        531441.    ,  456976.    ,  390625.    ,  331776.    ,
        390625.    ,  456976.    ,  194481.    ,   10000.    ,
         10000.    ,   14641.    ,    6561.    ,  531441.    ,
        614656.    ,  390625.    ,  390625.    ,       0.    ,
        130321.    ,   65536.    ,   83521.    ,  130321.    ,
        104976.    ,   38416.    ,   38416.    ,   38416.    ,
         38416.    ,   20736.    ,   28561.    ,   28561.    ,
        104976.    ,  234256.    ,  130321.    ,  104976.    ,
        279841.    ,  614656.    ,  810000.    ,  810000.    ,
        923521.    , 1500625.    ,  531441.    ,  45697

In [7]:
np.sqrt(mpg)

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [8]:
horsepower.sum()

42033.0

In [51]:
horsepower.min()

0.0

In [10]:
horsepower.max()

230.0

In [11]:
np.median(horsepower)

93.5

In [18]:
vals,counts = np.unique(horsepower, return_counts=True)
index = np.argmax(counts)
vals[index]

150.0

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [19]:
acceleration[0:5]

array([12. , 11.5, 11. , 12. , 10.5])

In [21]:
#Not sure if you wanted every other element but the first five or every other element in the array.
#I did both below
acceleration[5:]

array([10. ,  9. ,  8.5, 10. ,  8.5, 17.5, 11.5, 11. , 10.5, 11. , 10. ,
        8. ,  8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5,
       14.5, 17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. ,
       19. , 20. , 13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. ,
       11.5, 12. , 12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5,
       19. , 18. , 19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. ,
       13.5, 13. , 11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. ,
       14. , 14.5, 18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. ,
       11.5, 13. , 14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. ,
       16.5, 18. , 16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. ,
       19. , 19.5, 16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5,
       14. , 15.5, 11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. ,
       16.5, 21. , 17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5,
       16.5, 15.5, 14.5, 16.5, 19. , 14.5, 15.5, 14

In [29]:
acceleration[::2]

array([12. , 11. , 10.5,  9. , 10. , 17.5, 11. , 11. ,  8. ,  9.5, 15. ,
       15.5, 14.5, 17.5, 17.5, 15. , 15. , 18.5, 15.5, 19. , 13. , 15.5,
       15.5, 11.5, 13. , 12. , 13.5, 15. , 14. , 19.5, 19. , 19. , 15.5,
       23.5, 16.5, 12. , 13. , 11. , 13.5, 13.5, 14. , 14. , 18. , 18. ,
       17. , 15. , 13. , 13. , 12.5, 12. , 14.5, 11. , 16.5, 16. , 16. ,
       14. , 13. , 15. , 19.5, 13.5, 14. , 13. , 19.5, 14. , 11. , 13.5,
       16.5, 16. , 19. , 21. , 17. , 16.5, 14.5, 16. , 16.5, 14.5, 19. ,
       15.5, 15. , 16. , 16. , 19.5, 14. , 13.5, 18.5, 19. , 13.5, 16. ,
       16. , 13.5, 17. , 14. , 15. , 14.5, 17.5, 16.9, 17.7, 13. , 13.9,
       15.4, 17.6, 22.2, 14.2, 17.7, 16.2, 12.2, 16.4, 15.7, 21.9, 16.7,
       12. , 14. , 14.8, 15.5, 12.5, 13.7, 16.4, 17.7, 11.1, 12.2, 14.5,
       18.2, 17. , 16.4, 14.5, 13.5, 14.4, 18.6, 15.5, 12.8, 18.2, 15.4,
       17.2, 16.7, 15.1, 13.4, 13.7, 14.2, 14.5, 16.7, 14.9, 13.6, 15.8,
       16.6, 18.2, 18.2, 15.4, 13.2, 14.9, 15. , 14

8. Show how to select the number `99` in the array below. 

In [13]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [24]:
select_99[1,2]

99

9. Select the last element in each subarray (do this with one operation.)

In [25]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [26]:
select_more[:,2]

array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [28]:
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [31]:
np.log(mpg)

array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [32]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [65]:
np_2d = np.array([cylinders, horsepower])
print(np_2d.shape)
print(np_2d.ndim)
np_2d

(2, 406)
2


array([[  8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   4.,
          8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   4.,   6.,
          6.,   6.,   4.,   4.,   4.,   4.,   4.,   4.,   6.,   8.,   8.,
          8.,   8.,   4.,   4.,   4.,   4.,   4.,   6.,   6.,   6.,   6.,
          6.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   6.,   4.,   6.,
          6.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,
          4.,   4.,   4.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,
          8.,   3.,   8.,   8.,   8.,   8.,   4.,   4.,   4.,   4.,   4.,
          4.,   4.,   4.,   4.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,
          8.,   8.,   8.,   8.,   8.,   6.,   6.,   6.,   6.,   6.,   4.,
          8.,   8.,   8.,   8.,   6.,   4.,   4.,   4.,   3.,   4.,   6.,
          4.,   8.,   8.,   4.,   4.,   4.,   4.,   8.,   4.,   6.,   8.,
          6.,   6.,   6.,   6.,   4.,   4.,   4.,   4.,   6.,   6.,   6.,
          8.,   8.,   8.,   8.,   8., 

In [82]:
np_3d = np.array([[car], [cylinders], [horsepower]])
print(np_3d.shape)
print(np_3d.ndim)
np_3d

(3, 1, 406)
3


array([[['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
         'Plymouth Satellite', ..., 'Dodge Rampage', 'Ford Ranger',
         'Chevy S-10']],

       [[8, 8, 8, ..., 4, 4, 4]],

       [[130.0, 165.0, 150.0, ..., 84.0, 79.0, 82.0]]], dtype=object)

In [83]:
np_4d = np.array([[[car], [cylinders]], [[horsepower], [origin]]])
print(np_4d.shape)
print(np_4d.ndim)
np_4d

(2, 2, 1, 406)
4


array([[[['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
          'Plymouth Satellite', ..., 'Dodge Rampage', 'Ford Ranger',
          'Chevy S-10']],

        [[8, 8, 8, ..., 4, 4, 4]]],


       [[[130.0, 165.0, 150.0, ..., 84.0, 79.0, 82.0]],

        [['US', 'US', 'US', ..., 'US', 'US', 'US']]]], dtype=object)

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [47]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [48]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [67]:
#An identity matrix is a square matrix with ones on the main diagonal
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [70]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [71]:
transpose_me.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [49]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
#The multiplication fails because the 2 arrays are not the same dimensions.
#See error message above when trying to run - shapes (3,3) and (2,3)

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [56]:
my_list = horsepower[origin == 'Europe']
my_list.mean()

78.78082191780823

5. On average are Japanse cars more fuel efficient than US cars? 

In [72]:
japan_list = mpg[origin == 'Japan']
print(japan_list.mean())
us_list = mpg[origin == 'US']
print(us_list.mean())

30.450632911392404
19.688188976377955


In [ ]:
#Yes, the average mpg for cars from Japan is 30 mpg versus the US with an average of 19.69 mpg.

6. What is the correlation coefficient of `mpg` and `weight`?

In [77]:
df1 = pd.DataFrame(mpg)
df2 = pd.DataFrame(weight)
correlation_mpg = df1.corr(method='pearson')
print(correlation_mpg)
correlation_weight = df2.corr(method='pearson')
print(correlation_weight)

     0
0  1.0
     0
0  1.0


7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
#You would prefer a np.array if you needed to perform mathematical operations over entire collections of values or arrays fast.

In [ ]:
#Use list if you need to keep track of a sequence of things, more everyday operations and learning and tasks.